/**
 * @file game_modes.h
 * @author Dhiraj Adhikary (IIT Guwahati)
 * @brief Logic controllers for all 11 dynamic game modes generated by the LLM.
 */

#pragma once
#include "engine_types.h"
#include <cstdlib>

using namespace std;

// ==========================================
// EMSCRIPTEN UI BRIDGES
// ==========================================
#ifdef __EMSCRIPTEN__
extern "C" { 
    void triggerGameOverUI(int finalScore); 
    void triggerVictoryUI(int finalScore); 
}
#endif

// ==========================================
// UTILITIES & INPUT HANDLING
// ==========================================

inline void AdvanceLevelOrWin(GameContext* ctx) {
    if (ctx->currentLevelIndex + 1 < (int)ctx->levelsConfig.size()) {
        ctx->levelAdvanceTimer = 90; 
        Mix_PlayChannel(-1, ctx->sfxCorrect, 0);
    } else {
        ctx->currentState = VICTORY;
        triggerVictoryUI(ctx->score); // Triggers JS Firebase Score Submission
    }
}

inline void SpawnParticles(GameContext* ctx, float x, float y, int count, SDL_Color color) {
    for (int i = 0; i < count; i++) {
        float vx = ((rand() % 100) / 10.0f) - 5.0f; float vy = ((rand() % 100) / 10.0f) - 5.0f;
        int life = 20 + (rand() % 20); ctx->particles.push_back({x, y, vx, vy, life, life, color});
    }
}

inline void UpdateParticles(GameContext* ctx) {
    for (int i = (int)ctx->particles.size() - 1; i >= 0; i--) {
        ctx->particles[i].x += ctx->particles[i].vx; ctx->particles[i].y += ctx->particles[i].vy; ctx->particles[i].life--;
        if (ctx->particles[i].life <= 0) ctx->particles.erase(ctx->particles.begin() + i);
    }
}

/// @brief Global input router. Handles keyboard and mouse events depending on the active game mode.
inline bool HandleInput(GameContext* ctx) {
    SDL_Event event;
    while (SDL_PollEvent(&event)) {
        if (event.type == SDL_QUIT) { ctx->gameIsRunning = false; return false; }
        
        // Auto-start BGM on first interaction (Browser policy compliance)
        if (!ctx->bgmStarted && (event.type == SDL_KEYDOWN || event.type == SDL_MOUSEBUTTONDOWN)) { 
            Mix_PlayMusic(ctx->bgm, -1); ctx->bgmStarted = true; 
        }
        
        // Telemetry Toggle
        if (event.type == SDL_KEYDOWN && event.key.keysym.sym == SDLK_F3) { ctx->showFps = !ctx->showFps; }

        if (ctx->currentState == MENU) {
            if (event.type == SDL_KEYDOWN || event.type == SDL_MOUSEBUTTONDOWN) {
                ctx->currentState = PLAYING;
                ctx->lastFrameTicks = SDL_GetTicks(); 
                ctx->accumulator = 0; 
                Mix_PlayChannel(-1, ctx->sfxJump, 0); 
            }
            continue; 
        }

        if (ctx->currentState != PLAYING || ctx->levelAdvanceTimer > 0) continue; 

        // Specific Input Processing By Mode
        if (ctx->gameMode == "typing_defense") {
            if (event.type == SDL_TEXTINPUT) ctx->typeBuffer += event.text.text;
            else if (event.type == SDL_KEYDOWN && event.key.keysym.sym == SDLK_BACKSPACE && !ctx->typeBuffer.empty()) ctx->typeBuffer.pop_back();
        }
        else if (ctx->gameMode == "memory_match" && event.type == SDL_MOUSEBUTTONDOWN) {
            if (ctx->secondClickIdx == -1) {
                int mx = event.button.x, my = event.button.y;
                for (size_t i = 0; i < ctx->cards.size(); i++) {
                    SDL_Point p = { mx, my };
                    if (SDL_PointInRect(&p, &ctx->cards[i].rect) && ctx->cards[i].state == 0) {
                        ctx->cards[i].state = 1; 
                        if (ctx->firstClickIdx == -1) ctx->firstClickIdx = (int)i; else { ctx->secondClickIdx = (int)i; ctx->flipTimer = 60; }
                        Mix_PlayChannel(-1, ctx->sfxJump, 0); break;
                    }
                }
            }
        }
        else if (ctx->gameMode == "quiz_mcq" && event.type == SDL_MOUSEBUTTONDOWN) {
            int mx = event.button.x, my = event.button.y; SDL_Point p = { mx, my };
            for (auto& opt : ctx->currentQuizOptions) {
                if (SDL_PointInRect(&p, &opt.rect) && opt.state == 0) {
                    if (opt.isCorrect) {
                        opt.state = 2; ctx->score += 100; SpawnParticles(ctx, opt.rect.x + opt.rect.w/2, opt.rect.y + opt.rect.h/2, 50, {50, 255, 50, 255});
                        Mix_PlayChannel(-1, ctx->sfxCorrect, 0); AdvanceLevelOrWin(ctx); 
                    } else {
                        opt.state = 1; ctx->score -= 20; SpawnParticles(ctx, opt.rect.x + opt.rect.w/2, opt.rect.y + opt.rect.h/2, 20, {255, 50, 50, 255});
                        Mix_PlayChannel(-1, ctx->sfxWrong, 0);
                    }
                }
            }
        }
        else if (ctx->gameMode == "tug_of_war" && event.type == SDL_KEYDOWN && event.key.keysym.sym == SDLK_SPACE) {
            ctx->ropePosition -= ctx->playerPullPower; ctx->score += 10; Mix_PlayChannel(-1, ctx->sfxJump, 0); SpawnParticles(ctx, ctx->ropePosition, 300, 5, {50, 255, 50, 255});
        }
        else if (ctx->gameMode == "rhythm_catch" && event.type == SDL_KEYDOWN) {
            float targetX = -1;
            if (event.key.keysym.sym == SDLK_d) targetX = 250.0f; else if (event.key.keysym.sym == SDLK_f) targetX = 350.0f; else if (event.key.keysym.sym == SDLK_j) targetX = 450.0f; else if (event.key.keysym.sym == SDLK_k) targetX = 550.0f;
            if (targetX > 0) {
                for (auto& n : ctx->notes) {
                    if (n.active && abs(n.x - targetX) < 10 && n.y > 450 && n.y < 550) {
                        n.active = false; ctx->score += 50; Mix_PlayChannel(-1, ctx->sfxCorrect, 0); SpawnParticles(ctx, n.x+25, 500, 20, {0, 255, 255, 255}); break;
                    }
                }
            }
        }
    }
    return true;
}

// ==========================================
// GAME MODE UPDATE LOOPS
// ==========================================

inline void UpdateRunnerMode(GameContext* ctx) {
    UpdateParticles(ctx); const Uint8* keys = SDL_GetKeyboardState(NULL);
    if (keys[SDL_SCANCODE_R]) { if (!ctx->historyPlayer.empty()) { ctx->player = ctx->historyPlayer.back(); ctx->historyPlayer.pop_back(); ctx->obstacles = ctx->historyObs.back(); ctx->historyObs.pop_back(); ctx->isRewinding = true; return; } }
    ctx->isRewinding = false; int mx, my; Uint32 mState = SDL_GetMouseState(&mx, &my); bool isClicking = (mState & SDL_BUTTON(SDL_BUTTON_LEFT));
    if ((keys[SDL_SCANCODE_SPACE] || keys[SDL_SCANCODE_W] || keys[SDL_SCANCODE_UP] || isClicking) && ctx->player.onGround) { ctx->player.velocityY = -16.0f; Mix_PlayChannel(-1, ctx->sfxJump, 0); SpawnParticles(ctx, ctx->player.x + 20, ctx->player.y + 40, 15, {200, 200, 200, 255}); }
    ctx->player.UpdatePhysics(ctx->platform.y); ctx->obsTimer++;
    if (ctx->obsTimer > ctx->obsSpawnRate) { int obsHeight = 30 + (rand() % 30); ctx->obstacles.push_back({ 800.0f, ctx->platform.y - obsHeight, ctx->obsSpeed, 30, obsHeight, true, false }); ctx->obsTimer = 0 - (rand() % 30); }
    for (auto& obs : ctx->obstacles) {
        if (!obs.active) continue; obs.x -= obs.speed; 
        if (CheckCollision(ctx->player.GetRect(), obs.GetRect())) { Mix_PlayChannel(-1, ctx->sfxWrong, 0); ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); return; }
        if (!obs.passedPlayer && obs.x + obs.width < ctx->player.x) { obs.passedPlayer = true; ctx->score += 10; ctx->obsSpeed += 0.1f; }
        if (obs.x + obs.width < 0) obs.active = false;
    }
    ctx->historyPlayer.push_back(ctx->player); ctx->historyObs.push_back(ctx->obstacles); if (ctx->historyPlayer.size() > 180) { ctx->historyPlayer.pop_front(); ctx->historyObs.pop_front(); }
    
    int target = 999999;
    if(ctx->levelsConfig[ctx->currentLevelIndex].contains("target_score") && ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].is_number()) target = ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].get<int>();
    if (ctx->score - ctx->levelScoreStart >= target && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx);
}

inline void UpdateAlgoMode(GameContext* ctx) {
    UpdateParticles(ctx); const Uint8* keys = SDL_GetKeyboardState(NULL);
    if (keys[SDL_SCANCODE_A]) ctx->player.velocityX = -6.0f; else if (keys[SDL_SCANCODE_D]) ctx->player.velocityX = 6.0f; else ctx->player.velocityX = 0.0f;
    ctx->player.UpdatePhysics(ctx->platform.y);
    for (auto& opt : ctx->algoOptions) {
        if (!opt.active) continue; opt.y += opt.speed;
        if (CheckCollision(ctx->player.GetRect(), opt.GetRect())) {
            if (opt.isCorrect) { ctx->score += 100; Mix_PlayChannel(-1, ctx->sfxCorrect, 0); SpawnParticles(ctx, ctx->player.x, ctx->player.y, 50, {50, 255, 50, 255}); AdvanceLevelOrWin(ctx); } 
            else { ctx->player.hp -= 50; opt.active = false; Mix_PlayChannel(-1, ctx->sfxWrong, 0); SpawnParticles(ctx, ctx->player.x, ctx->player.y, 30, {255, 50, 50, 255}); }
        }
        if (opt.y > 600) opt.active = false;
    }
    if (ctx->player.hp <= 0) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); }
}

inline void UpdateTypingMode(GameContext* ctx) {
    UpdateParticles(ctx); ctx->wordSpawnTimer++;
    if (ctx->wordSpawnTimer > 120) {
        string selectedWord = "err"; if (!ctx->vocabulary.empty()) selectedWord = ctx->vocabulary[rand() % ctx->vocabulary.size()];
        ctx->words.push_back({ (float)(rand() % 600 + 100), -30.0f, ctx->globalFallSpeed, selectedWord, true }); ctx->wordSpawnTimer = 0;
    }
    bool matchFound = false;
    for (auto& w : ctx->words) {
        if (!w.active) continue; w.y += w.speed;
        if (ctx->typeBuffer == w.text) { w.active = false; matchFound = true; ctx->score += 10; Mix_PlayChannel(-1, ctx->sfxCorrect, 0); SpawnParticles(ctx, w.x, w.y, 20, {100, 200, 255, 255}); }
        if (w.y > 550) { w.active = false; ctx->player.hp -= 10; Mix_PlayChannel(-1, ctx->sfxWrong, 0); SpawnParticles(ctx, w.x, 550, 30, {255, 50, 50, 255}); }
    }
    if (matchFound) ctx->typeBuffer = ""; if (ctx->player.hp <= 0) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); }
    
    int target = 999999;
    if(ctx->levelsConfig[ctx->currentLevelIndex].contains("target_score") && ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].is_number()) target = ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].get<int>();
    if (ctx->score - ctx->levelScoreStart >= target && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx);
}

inline void UpdateMemoryMode(GameContext* ctx) {
    UpdateParticles(ctx);
    if (ctx->flipTimer > 0) {
        ctx->flipTimer--;
        if (ctx->flipTimer == 0) {
            if (ctx->cards[ctx->firstClickIdx].matchId == ctx->cards[ctx->secondClickIdx].matchId) { ctx->cards[ctx->firstClickIdx].state = 2; ctx->cards[ctx->secondClickIdx].state = 2; ctx->score += 100; Mix_PlayChannel(-1, ctx->sfxCorrect, 0); SpawnParticles(ctx, ctx->cards[ctx->firstClickIdx].rect.x, ctx->cards[ctx->firstClickIdx].rect.y, 20, {50, 255, 50, 255}); } 
            else { ctx->cards[ctx->firstClickIdx].state = 0; ctx->cards[ctx->secondClickIdx].state = 0; Mix_PlayChannel(-1, ctx->sfxWrong, 0); }
            ctx->firstClickIdx = -1; ctx->secondClickIdx = -1;
        }
    }
    if (!ctx->cards.empty()) { bool allSolved = true; for (auto& c : ctx->cards) { if (c.state != 2) { allSolved = false; break; } } if (allSolved && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx); }
}

inline void UpdateTugOfWarMode(GameContext* ctx) {
    UpdateParticles(ctx); ctx->ropePosition += ctx->aiPullSpeed;
    if (ctx->ropePosition <= 200.0f && ctx->levelAdvanceTimer == 0) { AdvanceLevelOrWin(ctx); } 
    else if (ctx->ropePosition >= 600.0f) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); }
}

inline void UpdateRhythmMode(GameContext* ctx) {
    UpdateParticles(ctx); ctx->noteTimer++;
    if(ctx->noteTimer > ctx->obsSpawnRate) { float lanes[4] = {250.0f, 350.0f, 450.0f, 550.0f}; ctx->notes.push_back({lanes[rand()%4], -50.0f, true}); ctx->noteTimer = 0; }
    for(auto& n : ctx->notes) {
        if(!n.active) continue; n.y += ctx->globalFallSpeed;
        if(n.y > 600) { n.active = false; ctx->player.hp -= 10; Mix_PlayChannel(-1, ctx->sfxWrong, 0); }
    }
    if (ctx->player.hp <= 0) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); }
    
    int target = 999999;
    if(ctx->levelsConfig[ctx->currentLevelIndex].contains("target_score") && ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].is_number()) target = ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].get<int>();
    if (ctx->score - ctx->levelScoreStart >= target && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx);
}

inline void UpdateFlappyMode(GameContext* ctx) {
    UpdateParticles(ctx); const Uint8* keys = SDL_GetKeyboardState(NULL);
    if (keys[SDL_SCANCODE_SPACE]) { ctx->player.velocityY = -6.0f; SpawnParticles(ctx, ctx->player.x, ctx->player.y+ctx->player.height, 5, {200, 200, 200, 255}); }
    ctx->player.UpdatePhysics(600); 
    if(ctx->player.y >= 600 - ctx->player.height || ctx->player.y <= 0) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); return; }
    ctx->obsTimer++;
    if (ctx->obsTimer > ctx->obsSpawnRate) {
        int gapY = 150 + (rand() % 200); int gapH = 150;
        ctx->obstacles.push_back({ 800.0f, 0, ctx->obsSpeed, 50, gapY, true, false });
        ctx->obstacles.push_back({ 800.0f, (float)(gapY+gapH), ctx->obsSpeed, 50, 600-(gapY+gapH), true, false }); ctx->obsTimer = 0; 
    }
    for (auto& obs : ctx->obstacles) {
        if (!obs.active) continue; obs.x -= obs.speed; 
        if (CheckCollision(ctx->player.GetRect(), obs.GetRect())) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); return; }
        if (!obs.passedPlayer && obs.x + obs.width < ctx->player.x) { obs.passedPlayer = true; ctx->score += 5; } 
    }
    int target = 999999;
    if(ctx->levelsConfig[ctx->currentLevelIndex].contains("target_score") && ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].is_number()) target = ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].get<int>();
    if (ctx->score - ctx->levelScoreStart >= target && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx);
}

inline void UpdateBulletHellMode(GameContext* ctx) {
    UpdateParticles(ctx); const Uint8* keys = SDL_GetKeyboardState(NULL);
    if (keys[SDL_SCANCODE_A]) ctx->player.velocityX = -6.0f; else if (keys[SDL_SCANCODE_D]) ctx->player.velocityX = 6.0f; else ctx->player.velocityX = 0.0f;
    if (keys[SDL_SCANCODE_W]) ctx->player.velocityY = -6.0f; else if (keys[SDL_SCANCODE_S]) ctx->player.velocityY = 6.0f; else ctx->player.velocityY = 0.0f;
    ctx->player.x += ctx->player.velocityX; ctx->player.y += ctx->player.velocityY;
    if(ctx->player.x<0) ctx->player.x=0; if(ctx->player.x>760) ctx->player.x=760; if(ctx->player.y<0) ctx->player.y=0; if(ctx->player.y>560) ctx->player.y=560;
    
    ctx->obsTimer++;
    if(ctx->obsTimer > ctx->obsSpawnRate) {
        int r = rand()%3;
        if(r==0) ctx->obstacles.push_back({(float)(rand()%800), -20, 0, 15, 15, true, false}); 
        else if(r==1) ctx->obstacles.push_back({820, (float)(rand()%600), ctx->obsSpeed, 15, 15, true, false}); 
        else ctx->obstacles.push_back({-20, (float)(rand()%600), -ctx->obsSpeed, 15, 15, true, false}); 
        ctx->obsTimer = 0; ctx->score += 10;
    }
    for(auto& p : ctx->obstacles) {
        if(!p.active) continue; if(p.speed == 0) p.y += ctx->obsSpeed; else p.x -= p.speed;
        if (CheckCollision(ctx->player.GetRect(), p.GetRect())) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); return; }
    }
    int target = 999999;
    if(ctx->levelsConfig[ctx->currentLevelIndex].contains("target_score") && ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].is_number()) target = ctx->levelsConfig[ctx->currentLevelIndex]["target_score"].get<int>();
    if (ctx->score - ctx->levelScoreStart >= target && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx);
}

inline void UpdateBreakoutMode(GameContext* ctx) {
    UpdateParticles(ctx); const Uint8* keys = SDL_GetKeyboardState(NULL);
    if (keys[SDL_SCANCODE_A]) ctx->player.velocityX = -8.0f; else if (keys[SDL_SCANCODE_D]) ctx->player.velocityX = 8.0f; else ctx->player.velocityX = 0.0f;
    ctx->player.x += ctx->player.velocityX; if(ctx->player.x<0) ctx->player.x=0; if(ctx->player.x>800-ctx->player.width) ctx->player.x=800-ctx->player.width;
    
    ctx->ball.x += ctx->ball.velocityX; ctx->ball.y += ctx->ball.velocityY;
    if (ctx->ball.x <= 0 || ctx->ball.x + ctx->ball.width >= 800) ctx->ball.velocityX *= -1;
    if (ctx->ball.y <= 0) ctx->ball.velocityY *= -1;
    if (ctx->ball.y >= 600) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); return; }
    
    if (CheckCollision(ctx->ball.GetRect(), ctx->player.GetRect())) { ctx->ball.velocityY = -abs(ctx->ball.velocityY); ctx->ball.y = ctx->player.y - ctx->ball.height; Mix_PlayChannel(-1, ctx->sfxJump, 0); }
    for(auto it = ctx->bricks.begin(); it != ctx->bricks.end(); ) {
        if(CheckCollision(ctx->ball.GetRect(), *it)) {
            ctx->ball.velocityY *= -1; ctx->score += 50; SpawnParticles(ctx, it->x + it->w/2, it->y + it->h/2, 15, {50, 255, 255, 255}); Mix_PlayChannel(-1, ctx->sfxCorrect, 0); it = ctx->bricks.erase(it);
        } else { ++it; }
    }
    if(ctx->bricks.empty() && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx); 
}

inline void UpdatePrecisionMode(GameContext* ctx) {
    UpdateParticles(ctx); const Uint8* keys = SDL_GetKeyboardState(NULL);
    if ((keys[SDL_SCANCODE_SPACE] || keys[SDL_SCANCODE_W] || keys[SDL_SCANCODE_UP]) && ctx->player.onGround) { ctx->player.velocityY = -16.0f; Mix_PlayChannel(-1, ctx->sfxJump, 0); SpawnParticles(ctx, ctx->player.x + 20, ctx->player.y + 40, 15, {200, 200, 200, 255}); }
    ctx->player.UpdatePhysics(ctx->platform.y); bool allPassed = true;
    for (auto& obs : ctx->obstacles) {
        if (!obs.active) continue; obs.x -= obs.speed; allPassed = false;
        if (CheckCollision(ctx->player.GetRect(), obs.GetRect())) { ctx->currentState = GAME_OVER; triggerGameOverUI(ctx->score); return; }
        if (!obs.passedPlayer && obs.x + obs.width < ctx->player.x) { obs.passedPlayer = true; ctx->score += 100; }
        if (obs.x + obs.width < 0) obs.active = false;
    }
    if (allPassed && !ctx->obstacles.empty() && ctx->levelAdvanceTimer == 0) AdvanceLevelOrWin(ctx); 
}